networks:
    app-tier:
        driver: bridge

services:

    # This will create the database image along with its element inside the container, which is split from the web image.   
    db:
        image: database
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: login-db
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ROOT_HOST: '%'

        build: db
        ports:
            - 3307:3306
        networks:
            - app-tier
        container_name: database

    # This will create the web image along with its element inside the container, which is split from the database image.
    web:
        image: webapp
        build: .
        ports:
            - 7000:7000
        volumes:
            - ./views:/usr/src/app
        networks:
            - app-tier
        depends_on:
            - db
        container_name: web_app